apiVersion: v1
kind: Service
metadata:
  name: Govrix Scout
  namespace: Govrix Scout
spec:
  selector:
    app: Govrix Scout
  ports:
  - name: proxy
    port: 4000
    targetPort: 4000
  - name: api
    port: 4001
    targetPort: 4001
